siteTitle = "Gatstrap"
siteDescr = "Gatsby starter for bootstrap a blog"
siteAuthor = "jaxx2104"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/gatstrap"
